# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b395b9d792bd58dd7cee895dec1689b99026d7f77b21a17d1a4a2e23e8f36827b85ea7886c4624d0622998b233f463f1fbf494b9f7e72d97f39aedf9799c7c99

test:
  secret_key_base: d5f212c480eb026c7a918ff0a2555e5ebd0682e5a6d4d8cfb98887001a410745d390ca029014f5d5aa37347dc764065baef39102b4ec461c6aee636df938ca16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
